#ifndef AMITY_SPS_INC_RESOLVER_TYPES
#define AMITY_SPS_INC_RESOLVER_TYPES

// Plug payload layout (matches VRCFury plug cell payload)
#define SPS_PLUG_PAYLOAD_RESERVED 0
#define SPS_PLUG_PAYLOAD_SOCKET_ID 1
#define SPS_PLUG_PAYLOAD_CHAIN_COUNT 2
#define SPS_PLUG_PAYLOAD_CHAIN_START 3
#define SPS_PLUG_PAYLOAD_CHAIN_MAX 5

#define SPS_PLUG_PAYLOAD_TANGENT_IN_START 8
#define SPS_PLUG_PAYLOAD_TANGENT_OUT_START 11

#endif
